### PR TITLE
Add check that the module is enabled before acting in __construct

### LINKED ISSUE #4: Module forces "Auto-numbering for records" to stay on even after the module is disabled in certain versions of REDCap.
This bug appears in REDCap 10.5.1 but not in 10.3.3 or earlier

The module causes projects to be unable to disable "Auto-numbering for records", even after the module is disabled on the project.

To recreate:

1. Create a project
1. Activate EM but NOT on project
~~1. Activate module on project~~
~~1. Configure the module:~~
    ~~- **Record auto-numbering option**: Choose first option~~
    ~~- **Specify the first record id**: Set to any number (e.g. 1000)~~
~~1. Create a new record and Save and Stay~~
~~1. Disable the module~~
1. Go back to project setup and disable "Auto-numbering for records" under Optional
1. Reload the page
1. Observe that Auto-numbering is enabled

**UPDATE**: This bug affects every project so long as the module is enabled at the system level.

___

The `construct` function runs whether the module is enabled or not: https://github.com/ctsit/record_autonumbering/blob/7aa41df8fe8c64a1d44069fbe051d9f048d20299/RecordAutonumber.php#L45

This sql statement is to blame:
https://github.com/ctsit/record_autonumbering/blob/7aa41df8fe8c64a1d44069fbe051d9f048d20299/RecordAutonumber.php#L85

### PR DESCRIPTION
**Pull request by ChemiKyle**
Closes #4

### CODE REVIEW

**Comment by michael-bentz** [comment]
I can't reproduce the issue following the steps listed [here](https://github.com/ctsit/record_autonumbering/issues/4). Is something setting `$this->project_id` that makes the following condition pass when not on a project page?
https://github.com/ctsit/record_autonumbering/blob/b11765cd83bebda6a5be9b42afa0d44b7d788d73/RecordAutonumber.php#L57
***
Also the added check:
https://github.com/ctsit/record_autonumbering/blob/b11765cd83bebda6a5be9b42afa0d44b7d788d73/RecordAutonumber.php#L59

prevents the following from ever being executed:
https://github.com/ctsit/record_autonumbering/blob/b11765cd83bebda6a5be9b42afa0d44b7d788d73/RecordAutonumber.php#L85-L94

The added check alters the behavior of the module. Instead of having `auto_inc_set` set to `1` after enabling the module for the project, `auto_inc_set` will still be set to `0` because the `else` block never gets called.

**Comment by michael-bentz** [comment]
The ``__construct()`` method gets called for different events despite being run from `REDCap 10.5.1`.
https://github.com/ctsit/record_autonumbering/blob/b11765cd83bebda6a5be9b42afa0d44b7d788d73/RecordAutonumber.php#L45-L46

This might have something to do with the different versions of PHP:
__Kyle's RedCap server info:__
>10 5 1 REDCap Server Info - KC

__My RedCap server info:__
>10 5 1 REDCap Server Info- MB

I need a snapshot of the same REDCap 10.5.1 to test.

**Comment by pbchase** [comment]
@tlstoffs and I tested this in Prod. While the module did not impose itself on projects where it was not enabled, we did get this error as we attempted to configure it on a module at the project level.  It happened after selecting the second option and choosing save. 

```
REDCap crashed due to an unexpected PHP fatal error!

Error message: Class MCRI\RecordAutonumber\PrefixAndPad contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (MCRI\RecordAutonumber\AbstractAutonumberGenerator::getRequiredDataEntryFields)
File: /var/www.backup/redcap-20201208T2046/modules/record_autonumbering_v0.0.0/AutonumberGenerators/PrefixAndPad.php
Line: 0
```

The project wherein I configured the PrefixAndPad now crashes whenever the module is enabled and we access the External Modules page or record_status_dashboard

We also saw other events wherein the module was disabled at the system level, yet we got no error message. One happened when I saved the configuration using the Unix timestamp option. Weird stuff.

**Comment by ChemiKyle** [comment]
I can successfully recreate this bug in a local instance. It occurs on the develop branch as well ~~(after initiating it on the current PR)~~.

**Comment by ChemiKyle** [comment]
This crash is fixed in the latest commit, though if you intended to leave "Specify a fixed prefix (can be blank)" blank, you'll get an annoying popup on the config page:  

image

I have an issue open since it's not clear what Luke's intent for that field is: https://github.com/lsgs/redcap-record-autonumbering/issues/8. If we want it blank, we can simply remove the offending block.

**Review by michael-bentz — COMMENTED** [review]
During testing, `__construct()` only gets called when the module is enabled or disabled at the project level, not when the module is only enabled in the `Control Center`. Because of that, the additional check `if (!$this->getProjectSettings()['enabled']['value']) return;` is redundant. In my case, line 64 handles that. 

Also the added checks prevents the following else block from ever executing:
```
} else {
        // not enabled - currently enabling so ensure project setting is autonumbering
        $sql = "update redcap_projects set auto_inc_set=1 where auto_inc_set=0 and project_id=".db_escape($this->project_id);
        $q = db_query($sql);
//                                        if (db_affected_rows()==1) {
        $nrows = db_affected_rows();
        if ($nrows==1) {
\Logging::logEvent($sql,"redcap_projects","MANAGE",$this->project_id,"project_id = $this->project_id","Modify project settings");
        }
}
```

resulting in the `auto_inc_set` being set to `0` for the project instead of `1` regardless of whether the module is enabled or disabled. I am not sure of the impact, but the module behavior is altered.

**Comment by ChemiKyle** [comment]
@mbentz-uf 
The issue stems from that `if-else` block, when the module is not enabled in a project, `auto_inc_set` is set to 1.  
`auto_inc_set` is tied to the project's autonumbering setting:
image

Turning this on for projects where the module was not active is the original bug. This PR has just snowballed a bit.  
Also, Taryn and I discovered that merely flipping the `auto_inc_set` toggle in the db is insufficient if the project had it turned off, so this PR will be updated anyway.

**Review by michael-bentz — APPROVED** [review]

**Pull request merged**
